### ISSUE TITLE
Always showing connecting... 

### ISSUE THREAD

**Issue by prataplalit90** [GleasonK/AndroidRTC#2]
After accepting incoming call... showing connecting.. but never connected

**Comment by GleasonK** [comment]
Did you mean to close this? If you figured it out I'm interested to know, I had some trouble finding a universal solution to this

**Comment by wingoku** [comment]
All of a sudden this issue has started occuring for me as well. It was working yesterday but now it is stuck at Connecting.

@GleasonK  What are the workarounds that you know? What is the reason for this behavior?
