### ISSUE TITLE
Doesn't work - stuck on connecting

### ISSUE THREAD

**Issue by wildeyes** [GleasonK/AndroidRTC#9]
How can I debug this?

**Comment by havenvo** [comment]
The same issue here. After I clicked answer, both side show connecting ...

**Comment by leo-dias** [comment]
The same issue, never connect. There are some solution?

**Comment by androidWarlock** [comment]
same issue anyone solved it ?

**Comment by NovumInceptum** [comment]
No ideas yet?

**Comment by mkmlh** [comment]
same issue here
The thing is, if u connect from smartphone into the web (https://kevingleason.me/AndroidRTC/) it works.
But i don't know the reasons.. yet.
